# Generated by Django 3.0.7 on 2020-09-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_raitingmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='generalRaiting',
            field=models.IntegerField(null=True),
        ),
    ]
