# Generated by Django 3.0.7 on 2020-09-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_generalraiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='raitingmovie',
            name='comment',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
