# Generated by Django 3.0.7 on 2020-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200917_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name="Movie's title"),
        ),
    ]
