# Generated by Django 3.0.7 on 2020-09-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200918_0311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaitingMovie',
            new_name='RatingMovie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='generalRaiting',
            new_name='generalRating',
        ),
        migrations.RenameField(
            model_name='ratingmovie',
            old_name='raiting',
            new_name='rating',
        ),
    ]
